[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = "1.0"
serde_json = "1.0"
lsp-types = "0.97"
rustc-hash = "2.1"
pretty_assertions = "1.4"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.benchmark]
inherits = "release"
debug = true
