[package]
name = "weblsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.7"
lsp-types = "0.97.0"
serde = "1.0.215"
serde_json = "1.0.133"
csslsrs = { version = "0.1.0", path = "../csslsrs" }
