blank_issues_enabled: false
contact_links:
  - name: Any ideas or suggestions?
    url: https://github.com/web-lsp/weblsp/discussions/categories/ideas
    about: Propose and discuss future improvements to WEBlsp.
  - name: Support or help needed?
    url: https://github.com/web-lsp/weblsp/discussions/categories/q-a
    about: Ask questions and get help from the community.
